apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance 
  namespace: openshift-logging 
spec:
  inputs:
   - name: special
     application:
      namespaces: 
       - my-devel  
  outputs:
   - name: special-output
     type: fluentdForward 
     url: 'tcp://fluentdserver.security.example.com:24224' 
   - name: leftover
     type: fluentdForward
     url: 'tcp://fluentdserver.home.example.com:24224'
  pipelines:
   - name: special-to-special
     inputRefs:  
     - special
     - audit
     outputRefs:
     - special-output
     labels:
       clusterId: C1234 
   - name: everythingelse
     inputRefs:
     - infrastructure
     - application
     outputRefs:
     - leftover
