apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: collector
    logging-infra: collector
    provider: openshift
  name: collector
  namespace: openshift-logging
spec:
  selector:
    matchLabels:
      component: collector
      logging-infra: collector
      provider: openshift
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        component: collector
        logging-infra: collector
        provider: openshift
      name: collector
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: info
        - name: VECTOR_SELF_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NODE_IPV4
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: quay.io/dciancio/vector
        imagePullPolicy: Always
        name: collector
        ports:
        - containerPort: 24231
          name: metrics
          protocol: TCP
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /etc/vector
          name: config
          readOnly: true
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /var/lib/ocp-collector
          name: filebufferstorage
        - mountPath: /var/run/ocp-collector/secrets/collector
          name: collector
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: cluster-logging
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: logcollector
      serviceAccountName: logcollector
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/disk-pressure
        operator: Exists
      volumes:
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - configMap:
          defaultMode: 420
          name: collector
        name: config
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
      - hostPath:
          path: /var/lib/ocp-collector
          type: ""
        name: filebufferstorage
      - name: collector
        secret:
          defaultMode: 420
          secretName: collector
          optional: true
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
