apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-logging-collector-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-logging-collector-read
subjects:
- kind: ServiceAccount
  name: logcollector
  namespace: openshift-logging
