apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: collector-metrics
  labels:
    logging-infra: support
  name: collector
  namespace: openshift-logging
spec:
  ports:
  - name: metrics
    port: 24231
    protocol: TCP
    targetPort: metrics
  selector:
    component: collector
    provider: openshift
  sessionAffinity: None
  type: ClusterIP
